---
title: "서론"
jupyter: python3
---

## \< 국내 여행의 의미 \>

-   공간의 범위 : 행정구역상 현 거주지를 벗어나 다른 지역(시/군)을 다녀온 모든 여행을 의미

-   활동의 범위:

1.  관광 여행\
    관광, 맛집 투어, 박물관, 전시 구경, 스포츠, 레저 체험 등의 모든 활동
2.  기타 여행\
    명절 귀성, 가족 행사, 출장, 업무 세미나 등 모든 활동

## \< 목적 \>

### 여행 패턴 분석

다양한 여행지에서 방문객의 여행 패턴을 분석하여, 인기 있는 여행지와 방문객이 선호하는 경로를 파악

### 시기별 트렌드 파악

특정 시기에 여행객이 선호하는 여행지와 여행 형태를 파악하여, 여행 산업에 대한 시기별 트렌드를 이해

------------------------------------------------------------------------

## \< 사용한 데이터 \>

### 1. 월별 여행 횟수

| **항목**      | **내용**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|-----------------|-------------------------------------------------------|
| **통계표명**  | 월별 국내여행 횟수                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| **조회기간**  | \[년\] 2018\~2022                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| **출처**      | 「국민여행조사」, 문화체육관광부                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| **통계표URL** | <https://kosis.kr/statHtml/statHtml.do?orgId=113&tblId=DT_113_STBL_1029207&conn_path=I3>                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| **단위**      | 천회                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| **속성**      | 1\. 시점 : 년, 월 <br> 2. 전체 합계 : 소계 <br> 3. 성별 : 남자, 여자 <br> 4. 연령 : 15\~19세, 20대, 30대, 40대, 50대, 60대, 70세 이상 <br> 5. 직업 : 임금봉급근로자, 고용원있는사업주, 고용원없는사업주, 고용원없는자영업자, 무급가족 종사자, 사무전문, 기술생산노무, 판매서비스, 자영업, 학생, 전업주부, 무직은퇴, 기타 <br> 6. 학력 : 초졸 이하, 중학교, 고등학교, 대학교이상 <br> 7. 가구원수 : 1인, 2인, 3인이상 <br> 8. 가구소득 : 100만원 미만, 100\~200만원 미만, 200\~300만원 미만, 300\~400만원 미만, 600만원 이상, 무응답 |

### 2. 관광 여행 정보 획득 경로

| **항목**      | **내용**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|-----------------|-------------------------------------------------------|
| **통계표명**  | 관광여행 정보 획득 경로                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| **조회기간**  | \[년\] 2018\~2022                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| **출처**      | 「국민여행조사」, 문화체육관광부                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| **통계표URL** | <https://kosis.kr/statHtml/statHtml.do?orgId=113&tblId=DT_113_STBL_1029487&conn_path=I3>                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| **단위**      | \%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| **속성**      | 1\. 시점 : 년 <br> 2. 전체 합계 : 소계 <br> 3. 성별 : 남자, 여자 <br> 4. 연령 : 15\~19세, 20대, 30대, 40대, 50대, 60대, 70세 이상 <br> 5. 직업 : 임금봉급근로자, 고용원있는사업주, 고용원없는사업주, 고용원없는자영업자, 무급가족 종사자, 사무전문, 기술생산노무, 판매서비스, 자영업, 학생, 전업주부, 무직은퇴, 기타 <br> 6. 학력 : 초졸 이하, 중학교, 고등학교, 대학교이상 <br> 7. 가구원수 : 1인, 2인, 3인이상 <br> 8. 가구소득 : 100만원 미만, 100\~200만원 미만, 200\~300만원 미만, 300\~400만원 미만, 600만원 이상, 무응답 |

### 3. 관광여행 방문지 선택이유(1순위)

| **항목**      | **내용**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|-----------------|-------------------------------------------------------|
| **통계표명**  | 관광여행 방문지 선택 이유 (1순위)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| **조회기간**  | \[년\] 2018\~2022                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| **출처**      | 「국민여행조사」, 문화체육관광부                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| **통계표URL** | <https://kosis.kr/statHtml/statHtml.do?orgId=113&tblId=DT_113_STBL_1029481&conn_path=I3>                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| **단위**      | \%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| **속성**      | 1\. 시점 : 년 <br> 2. 전체 합계 : 소계 <br> 3. 성별 : 남자, 여자 <br> 4. 연령 : 15\~19세, 20대, 30대, 40대, 50대, 60대, 70세 이상 <br> 5. 직업 : 임금봉급근로자, 고용원있는사업주, 고용원없는사업주, 고용원없는자영업자, 무급가족 종사자, 사무전문, 기술생산노무, 판매서비스, 자영업, 학생, 전업주부, 무직은퇴, 기타 <br> 6. 학력 : 초졸 이하, 중학교, 고등학교, 대학교이상 <br> 7. 가구원수 : 1인, 2인, 3인이상 <br> 8. 가구소득 : 100만원 미만, 100\~200만원 미만, 200\~300만원 미만, 300\~400만원 미만, 600만원 이상, 무응답 |

### 4. 지역별 관광지 검색 순위

| **항목**          | **내용**                                                         |
|-------------------|------------------------------------------------------------------|
| **통계표명**      | 내비게이션 데이터                                                |
| **조회기간**      | 2018년~2022년                                                    |
| **출처**          | 티맵 모빌리티㈜                                                  |
| **통계표URL**     | [링크](#)                                                        |
| **단위**          | n회                                                              |
| **속성**          | '순위', '광역시/도', '시/군/구', '관광지명', '도로명주소', '중분류 카테고리', '소분류 카테고리', '검색건수' |
